name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
    branches:
      - main
      - develop

jobs:
  clippy:
    uses: jontze/.workflows/.github/workflows/rust_clippy.yaml@main
    with:
      toolchain: stable

  lint:
    name: Lint
    uses: jontze/.workflows/.github/workflows/rust_lint.yaml@main
    with:
      toolchain: stable

  build:
    name: Build
    uses: jontze/.workflows/.github/workflows/rust_build.yaml@main
    with:
      toolchain: stable
